services:
  web:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh /app/start-dev.sh
    volumes:
      - ./backend:/app
    environment:
      DEBUG: "True"
      POSTGRES_HOST: db
